# Generated by Django 5.0 on 2024-03-10 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_test', '0003_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='table',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
