# Generated by Django 5.0 on 2024-03-15 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_test', '0004_event_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='access',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
