# Generated by Django 5.0 on 2024-03-16 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_test', '0005_teacher_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auth',
            name='id',
        ),
        migrations.AlterField(
            model_name='auth',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server_test.teacher'),
        ),
    ]
