# Generated by Django 5.0 on 2024-03-18 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_test', '0006_remove_auth_id_alter_auth_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auth',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server_test.teacher'),
        ),
    ]
