# Generated by Django 5.0 on 2024-03-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_test', '0007_alter_auth_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentwork',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentwork',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server_test.event'),
        ),
    ]
