# Generated by Django 5.0 on 2024-03-18 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_test', '0008_remove_studentwork_id_alter_studentwork_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='id',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='id',
        ),
        migrations.RemoveField(
            model_name='expertise',
            name='id',
        ),
        migrations.RemoveField(
            model_name='openclass',
            name='id',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='id',
        ),
        migrations.AlterField(
            model_name='course',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server_test.event'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server_test.event'),
        ),
        migrations.AlterField(
            model_name='expertise',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server_test.event'),
        ),
        migrations.AlterField(
            model_name='openclass',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server_test.event'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='server_test.event'),
        ),
    ]
