# Generated by Django 5.0 on 2024-04-22 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_test', '0010_teacher_department_alter_teacher_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selfed',
            name='begin',
        ),
        migrations.RemoveField(
            model_name='selfed',
            name='end',
        ),
        migrations.AddField(
            model_name='selfed',
            name='stage',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
