# Generated by Django 5.0 on 2024-05-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_test', '0011_remove_selfed_begin_remove_selfed_end_selfed_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='active',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
